[repository]
name = "collective-multiworkflow"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/collective/collective-multiworkflow"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "collective.multiworkflow"
path = "backend"
code_path = "src/collective/multiworkflow"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@plone-collective/volto-multiworkflow"
path = "frontend/packages/volto-multiworkflow"
code_path = "src"
changelog = "frontend/packages/volto-multiworkflow/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-multiworkflow/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "61a8f90e5408ce0a5337e3fdf6723369a4864ee8"
generated_date = "2026-08-07 19:03:59"
