"""Record the HTTP examples the REST API reference renders.

Every test here is a real assertion *and* a generator: it exercises the
endpoint, checks the one property the surrounding documentation claims, and
writes the request and response to ``http-examples/``. Keeping the two together
is the point — documentation generated by something the suite does not check
would be free to describe an endpoint that no longer exists.
"""

from collective.multiworkflow.demo.behavior import FOUNDATION_MEMBER_WORKFLOW
from tests import MEMBER_PROFILE
from tests import PLAIN_DOCUMENT
from tests import PUBLICATION_WORKFLOW
from tests.docs import save_example
from typing import Any

import pytest


pytestmark = pytest.mark.portal(
    content=[MEMBER_PROFILE, PLAIN_DOCUMENT],
    roles=["Manager"],
)

#: Transition of the example membership workflow, as the demo profile ships it.
ACTIVATE = "activate"


class TestWorkflowEndpoint:
    def test_workflow_get(self, docs_session: Any) -> None:
        """``@workflow`` describes every workflow in the chain."""
        response = save_example(
            "workflow_get",
            docs_session.get(f"/{MEMBER_PROFILE['id']}/@workflow"),
        )

        assert response.status_code == 200
        chain = response.json()["chain"]
        assert [entry["workflow_id"] for entry in chain] == [
            PUBLICATION_WORKFLOW,
            FOUNDATION_MEMBER_WORKFLOW,
        ]

    def test_workflow_get_without_additional_workflows(self, docs_session: Any) -> None:
        """Content nothing contributed to is served core's payload untouched.

        Not a chain of one: the serializer is registered for the participation
        marker, so non-participating content never reaches it and the payload
        carries no ``chain`` key at all.
        """
        response = save_example(
            "workflow_get_plain",
            docs_session.get(f"/{PLAIN_DOCUMENT['id']}/@workflow"),
        )

        assert response.status_code == 200
        assert "chain" not in response.json()

    def test_workflow_post(self, docs_session: Any) -> None:
        """A transition of an additional workflow is executed like any other."""
        response = save_example(
            "workflow_post",
            docs_session.post(f"/{MEMBER_PROFILE['id']}/@workflow/{ACTIVATE}"),
        )

        assert response.status_code == 200
        assert response.json()["review_state"] == "private"


class TestHistoryEndpoint:
    def test_history_get(self, docs_session: Any) -> None:
        """``@history`` reports every workflow's transitions in one stream."""
        transitioned = docs_session.post(
            f"/{MEMBER_PROFILE['id']}/@workflow/{ACTIVATE}"
        )
        assert transitioned.status_code == 200

        response = save_example(
            "history_get",
            docs_session.get(f"/{MEMBER_PROFILE['id']}/@history"),
        )

        assert response.status_code == 200
        recorded = {entry["workflow_id"] for entry in response.json()}
        assert FOUNDATION_MEMBER_WORKFLOW in recorded
